source 'https://rubygems.org'

gem 'dashing', github: 'kabisaict/dashing', ref: 'bdeb0'
gem 'nagiosharder', github: 'railsmachine/nagiosharder', ref: '5b35c'
gem 'bourbon', '~> 3.1.6'
gem 'httparty', '~> 0.8.3'
gem 'dotenv', '~> 0.7.0'
gem 'haml', '~> 4.0.3'
gem 'xml-simple', '~> 1.1.2'
gem 'nokogiri', '~> 1.6.0'
